name: Deploy scrapesome

on:
  push:
    branches:
      - main     # Triggers UI Docs deployment
    tags:
      - 'v*'  # Deploy only when pushing a version tag like v1.0.0

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')  # Only run for version tags
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        run: |
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

  deploy-ui-docs:
    if: github.ref == 'refs/heads/main'  # Only run on main branch
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build UI Docs
        run: mkdocs build --strict

      - name: Deploy UI Docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: UI-Documentation